name: Waka Readme

on:
  workflow_dispatch:
  schedule:
    # Runs at 00:00AM UTC
    - cron: '0 */1 * * *'

jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - uses: HEEJUICE/waka-readme-stats@master #PLEASE USE MASTER BRANCH
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_OS: "False"
          SHOW_SHORT_INFO: "False"  
          SHOW_PROFILE_VIEWS: "False" 
          SHOW_LINES_OF_CODE: "True"
          SHOW_PROJECTS: "False" 
          LOCALE: "en"
